version: "3.1"

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50 
    batch_size: 16
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    batch_size: 16

assistant_id: 20241017-163932-small-mile
